### ISSUE TITLE
Cryptonightv7

### ISSUE THREAD

**Issue by alexsggit** [KlausT/ccminer-cryptonight#69]
Hello,

did you planned to add support for cryptonightV7 POW? As you know some coins (monero, aeon, stellite, etc...) already forked to that new POW and, given that your miner is the best out there (for me at least) I really appreciate if you add V7 :-)

Best

**Comment by KlausT** [comment]
I have added an option now where you can choose between the old and the new algo.
`-a cryptonight` for the old algo (works for Graft right now, didn't test others)
`-a monero` for the new algo
I don't know yet if the other forked coins will use the exact same algo as Monero

**Comment by KlausT** [comment]
This will get ridiculous really fast if I have to add a special case for every coin.
Oh well, time to add another option, like `--forkversion`

**Comment by goldmang** [comment]
Hmm, what about cryptonight-heavy variant used by sumo?

**Comment by alexsggit** [comment]
Well, I rebuilt the miner from trunk (under Windows) and tried both cryptonight and monero -a switching options but it doesn't work for stellite :-(

Can you please fix it?

**Comment by KlausT** [comment]
Yeah. I just made a change.
It should work now when using the `-a stellite` option

**Comment by alexsggit** [comment]
Eureka! It works like a charm :-)
Thank you very much Klaus!

**Comment by nemosminer** [comment]
tested on nicehash cryptonightV7 stratum with -a  cryptonightV7 it works great... is this ok?

**Comment by Fjodor42** [comment]
Electroneum switched to cryptonightv7 very recently - when running with -a monero, I still get  `reject reason: Rejected share: invalid result`, though.

What can I do to help?
